export default [
  { id: "2", imageName: "сс_1.jpg", tag: "Cartoon characters" },
  { id: "3", imageName: "сс_2.jpg", tag: "Cartoon characters" },
  { id: "4", imageName: "сс_4.jpg", tag: "Cartoon characters" },
  { id: "5", imageName: "сс_5.jpg", tag: "Cartoon characters" },
  { id: "6", imageName: "сс_6.jpg", tag: "Cartoon characters" },
  { id: "8", imageName: "сс_8.jpg", tag: "Cartoon characters" },
  { id: "9", imageName: "сс_10.png", tag: "Cartoon characters" },
  { id: "10", imageName: "dp_1.jpg", tag: "Digital portraits" },
  { id: "11", imageName: "dp_2.jpg", tag: "Digital portraits" },
  { id: "12", imageName: "dp_3.jpg", tag: "Digital portraits" },
  { id: "13", imageName: "dp_4.jpg", tag: "Digital portraits" },
  { id: "14", imageName: "dp_5.jpg", tag: "Digital portraits" },
  { id: "15", imageName: "dp_6.jpg", tag: "Digital portraits" },
  { id: "16", imageName: "dp_7.jpg", tag: "Digital portraits" },
  { id: "17", imageName: "dp_8.jpg", tag: "Digital portraits" },
  { id: "18", imageName: "dp_9.jpg", tag: "Digital portraits" },
  { id: "20", imageName: "vp_1.jpg", tag: "Vector portraits" },
  { id: "21", imageName: "vp_2.jpg", tag: "Vector portraits" },
  { id: "22", imageName: "vp_6.jpg", tag: "Vector portraits" },
  { id: "23", imageName: "vp_3.jpg", tag: "Vector portraits" },
  { id: "24", imageName: "vp_4.jpg", tag: "Vector portraits" },
  { id: "25", imageName: "vp_5.jpg", tag: "Vector portraits" },
  { id: "26", imageName: "vc_1.jpg", tag: "Vector portraits" },
  { id: "27", imageName: "vc_2.jpg", tag: "Vector portraits" },
  { id: "28", imageName: "vc_93.jpg", tag: "Vector portraits" },
  { id: "29", imageName: "lf_1.jpg", tag: "Posters" },
  { id: "30", imageName: "lf_2.jpg", tag: "Posters" },
  { id: "31", imageName: "lf_3.jpg", tag: "Posters" },
  { id: "32", imageName: "lf_4.jpg", tag: "Posters" },
  { id: "33", imageName: "lf_7.jpg", tag: "Posters" },
  { id: "34", imageName: "lf_8.jpg", tag: "Posters" },
  { id: "35", imageName: "lf_9.jpg", tag: "Posters" },
  { id: "36", imageName: "lf_10.jpg", tag: "Posters" },
  { id: "37", imageName: "lf_11.jpg", tag: "Posters" },
  { id: "38", imageName: "lf_12.jpg", tag: "Posters" },
  { id: "39", imageName: "lf_13.jpg", tag: "Posters" },
  { id: "40", imageName: "lf_14.jpg", tag: "Posters" },
  { id: "41", imageName: "lf_15.jpg", tag: "Posters" },
  { id: "42", imageName: "lf_16.jpg", tag: "Posters" },
  { id: "43", imageName: "lf_17.jpg", tag: "Posters" },
  { id: "44", imageName: "gdc_1.jpg", tag: "Game design" },
  { id: "45", imageName: "gdc_2.jpg", tag: "Game design" },
  { id: "46", imageName: "gdc_3.jpg", tag: "Game design" },
  { id: "47", imageName: "gdc_4.jpg", tag: "Game design" },
  { id: "48", imageName: "gdc_5.jpg", tag: "Game design" },
  { id: "49", imageName: "gdc_10.jpg", tag: "Game design" },
  { id: "50", imageName: "gdc_11.jpg", tag: "Game design" },
  { id: "51", imageName: "gdC_6.jpg", tag: "Game design" },
  { id: "52", imageName: "gdC_7.jpg", tag: "Game design" },
  { id: "53", imageName: "gdC_8.jpg", tag: "Game design" },
  { id: "54", imageName: "gdC_9.jpg", tag: "Game design" },
  { id: "55", imageName: "gdC_93.jpg", tag: "Game design" },
];
